# This is a basic workflow to help you get started with Actions

name: gestureClassify

# Controls when the action will run. 
on:
  workflow_dispatch: # 手动触发
  

jobs:

  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
      # 检出
      - name: Checkout
        uses: actions/checkout@v2
        
      # 环境
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # 安装依赖项
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
      
      # 执行
      - name: 'execute'
        run: ./run_demo_hand_with_tracker.py
        
     
